"""set server default for job status

Revision ID: 77e819f6df6f
Revises: f9277b997665
Create Date: 2020-09-25 13:37:46.921616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e819f6df6f'
down_revision = 'f9277b997665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_open', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_open')
    # ### end Alembic commands ###
