"""add job status

Revision ID: 8d3e3f8931e6
Revises: f9277b997665
Create Date: 2020-09-25 13:26:43.630918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3e3f8931e6'
down_revision = 'f9277b997665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_open', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_open')
    # ### end Alembic commands ###
