"""change default time

Revision ID: 9d08720e602f
Revises: 39aef3381ba8
Create Date: 2020-09-24 11:34:50.306383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d08720e602f'
down_revision = '39aef3381ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
