"""add brief to job

Revision ID: cf32c5928920
Revises: fb655f49e038
Create Date: 2020-10-19 08:44:18.165230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf32c5928920'
down_revision = 'fb655f49e038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'brief')
    # ### end Alembic commands ###
