"""init db

Revision ID: f4466581ae12
Revises: 
Create Date: 2020-09-21 18:54:45.999285

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4466581ae12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('salary', sa.Float(), nullable=False),
                    sa.Column('address', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('user_type', sa.String(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('phone_number', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('employees',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('employers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('code', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('address', sa.Text(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_employers_code'), 'employers', ['code'], unique=True)
    op.create_index(op.f('ix_employers_id'), 'employers', ['id'], unique=False)
    op.create_index(op.f('ix_employers_name'), 'employers', ['name'], unique=True)
    op.create_index(op.f('ix_employers_user_id'), 'employers', ['user_id'], unique=False)
    op.create_table('job_tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_job_tags_id'), 'job_tags', ['id'], unique=False)
    op.create_index(op.f('ix_job_tags_job_id'), 'job_tags', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_tags_tag_id'), 'job_tags', ['tag_id'], unique=False)
    op.create_table('applies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('employee_id', sa.Integer(), nullable=False),
                    sa.Column('job_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('cv', sa.Text(), nullable=False),
                    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='applystatus'), nullable=False),
                    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_applies_employee_id'), 'applies', ['employee_id'], unique=False)
    op.create_index(op.f('ix_applies_id'), 'applies', ['id'], unique=False)
    op.create_index(op.f('ix_applies_job_id'), 'applies', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applies_job_id'), table_name='applies')
    op.drop_index(op.f('ix_applies_id'), table_name='applies')
    op.drop_index(op.f('ix_applies_employee_id'), table_name='applies')
    op.drop_table('applies')
    op.drop_index(op.f('ix_job_tags_tag_id'), table_name='job_tags')
    op.drop_index(op.f('ix_job_tags_job_id'), table_name='job_tags')
    op.drop_index(op.f('ix_job_tags_id'), table_name='job_tags')
    op.drop_table('job_tags')
    op.drop_index(op.f('ix_employers_user_id'), table_name='employers')
    op.drop_index(op.f('ix_employers_name'), table_name='employers')
    op.drop_index(op.f('ix_employers_id'), table_name='employers')
    op.drop_index(op.f('ix_employers_code'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
