"""update relationships one-one user and employer, employee

Revision ID: f9277b997665
Revises: 19bb38433aec
Create Date: 2020-09-24 13:30:00.757879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9277b997665'
down_revision = '19bb38433aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.add_column('employers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employers', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_employee_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_employer_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'employer_id')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_employer_id_fkey', 'users', 'employers', ['employer_id'], ['id'])
    op.create_foreign_key('users_employee_id_fkey', 'users', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.drop_column('employers', 'user_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
