"""add job slug

Revision ID: fb655f49e038
Revises: 77e819f6df6f
Create Date: 2020-10-18 21:05:04.183776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb655f49e038'
down_revision = '77e819f6df6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('slug', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'slug')
    # ### end Alembic commands ###
